AWSTemplateFormatVersion: '2010-09-09'
Description: ec2 create

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh enable
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Restrict this in production environments

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0807bd3aff0ae7273
      InstanceType: t3.micro
      KeyName: ohio-new-11
      SecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId # Associates the Security Group
      Tags:
        - Key: Name
          Value: Amit-sys
